# Generated by Django 2.1.7 on 2019-04-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_visualizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='curtidas',
            field=models.IntegerField(default=0),
        ),
    ]
