# Generated by Django 2.2.1 on 2019-05-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_rascunho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
