# Generated by Django 2.2.1 on 2019-05-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190530_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='curtidas',
        ),
        migrations.AddField(
            model_name='produto',
            name='curtidas',
            field=models.IntegerField(default=0),
        ),
    ]
