# Generated by Django 2.2.1 on 2019-06-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_produto_descurtidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visualizacoes',
        ),
        migrations.AddField(
            model_name='produto',
            name='visualizacoes',
            field=models.IntegerField(default=0),
        ),
    ]
