# Generated by Django 2.2.1 on 2019-06-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
