# Generated by Django 2.2.1 on 2019-06-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
    ]
