# Generated by Django 2.2.1 on 2019-06-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Aperitivos', 'Aperitivos'), ('Bebidas', 'Bebidas'), ('Biscoitos', 'Biscoitos'), ('Carnes', 'Carnes'), ('Massas', 'Massas')], max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('UN', 'UN'), ('PC', 'PC'), ('KG', 'KG'), ('LT', 'LT'), ('PÇ', 'PÇ')], max_length=2),
        ),
    ]
