# Generated by Django 2.2.1 on 2019-06-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190621_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.FileField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
